[tool.black]
line-length = 100
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | env
)/
'''

[tool.ruff]
line-length = 100
exclude = ["venv", ".venv", "env"]

[tool.isort]
profile = "black"
line_length = 100
skip = ["venv", ".venv", "env"]
